urlweb:           "https://cbkadal.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/cbkadal/os211/"
urlghpage:        "https://cbkadal.github.io/os211/"
keywords:         "jekyll, testing"

