urlweb:           "https://fadhilrasendriya.github.io/os211/"
urlgithub:        "https://github.com/fadhilrasendriya/os211/"
urlghpage:        "https://fadhilrasendriya.github.io/os211/"
keywords:         "jekyll, testing"

